using Volo.Abp;

namespace EnglishLearningPlatformApp.EntityFrameworkCore;

public abstract class EnglishLearningPlatformAppEntityFrameworkCoreTestBase : EnglishLearningPlatformAppTestBase<EnglishLearningPlatformAppEntityFrameworkCoreTestModule>
{

}
