using Xunit;

namespace EnglishLearningPlatformApp.EntityFrameworkCore;

[CollectionDefinition(EnglishLearningPlatformAppTestConsts.CollectionDefinitionName)]
public class EnglishLearningPlatformAppEntityFrameworkCoreCollection : ICollectionFixture<EnglishLearningPlatformAppEntityFrameworkCoreFixture>
{

}
